### PR TITLE
Rename Active Jobs application.js.erb to application.js

### PR DESCRIPTION
**Pull request by msquee**
* Remove redundant dependency `jquery-migrate`
* Remove unused file `pages.js.coffee`

`application.js.erb` renamed to `application.js` because we do not use any Ruby in this file.

### CODE REVIEW

**Comment by johrstrom** [comment]
Surprisingly, this just works. I guess we didn't use any deprecated jquery apis!?

We download all the js assets separately now. I wonder if there's a way to bundle them to decrease traffic?

**Comment by ericfranz** [comment]
I'd keep jquery-migrate-3.1.0.min.js for now - unless we are going to test all of the interactive app examples that utilize jQuery and verify they work without this.

**Comment by ericfranz** [comment]
>We download all the js assets separately now. I wonder if there's a way to bundle them to decrease traffic?

They are separate in development mode and combined in production mode.

**Comment by msquee** [comment]
> I'd keep jquery-migrate-3.1.0.min.js for now - unless we are going to test all of the interactive app examples that utilize jQuery and verify they work without this.

Removing jquery-migrate only impacts the Active Jobs app, I added it back though!

**Pull request merged**
