### PR TITLE
migrate our portions of the file editor to webpack

### PR DESCRIPTION
**Pull request by johrstrom**
migrate our portions of the file editor to webpack. By our portions I mean our code. Ace which we currently store in public/ needs to be added to yarn.

### CODE REVIEW

**Review by gbyrketosc — CHANGES_REQUESTED** [review]
File editor is not functioning properly.

**Comment by johrstrom** [comment]
I believe I've fixed this and it's ready for review.  You can use the `.env.overload` to get it to save correctly.

```
[johrstrom dashboard(migrate/active_jobs.js)] 🐱  cat .env.overload 
OOD_FILES_URL="/pun/dev/dashboard/files"
OOD_EDITOR_URL="/pun/dev/dashboard/files"
```

**Comment by gbyrketosc** [comment]
> I believe I've fixed this and it's ready for review. You can use the `.env.overload` to get it to save correctly.
> 
> ```
> [johrstrom dashboard(migrate/active_jobs.js)] 🐱  cat .env.overload 
> OOD_FILES_URL="/pun/dev/dashboard/files"
> OOD_EDITOR_URL="/pun/dev/dashboard/files"
> ```

Functionality looks good.  Have a 2nd set of eyes looking as well.

**Comment by johrstrom** [comment]
Obviously I changed the navbar here to match what's on the dashboard. Longer term we need to stop using the editor layout and use application layout.

**Review by gbyrketosc — APPROVED** [review]
Functioning properly.

**Pull request merged**
