### PR TITLE
bundle install top level gems for e2e tests

### PR DESCRIPTION
**Pull request by johrstrom**
all our tests are failing because rspec gems doesn't exist anywhere. Hopefully this fixes that.

### CODE REVIEW

**Review by Oglopf — APPROVED** [review]
Looks good.

**Comment by johrstrom** [comment]
Tests still fail! It'll be ready when the e2e pass and of course we'll have to squash or remove all the intermediate tests to see stuff.

**Comment by johrstrom** [comment]
Looks like this is ready. Let's squash and merge this with a simple commit message: `fix builds because e2e tests run 'clean' which wipes relative vendor/ directories`.

**Review by Oglopf — APPROVED** [review]
Looks good.

**Pull request merged**
