### PR TITLE
Add ci

### PR DESCRIPTION
**Pull request by johrstrom**
This adds the spec file directly from the ondemand-packaging repo along with a gitlab-ci.yml that we can use to start building at the OSU gitlab.

### CODE REVIEW

**Comment by johrstrom** [comment]
Sorry, @treydock after you'd approved this, I double checked and noticed that artifacts where still enabled (this will cause builds to fail in code.osu.edu, though I've got a ticket open to increase the limit) and the logic to switch the SECTION paramater didn't work in the initial commit.

**Comment by treydock** [comment]
@johrstrom @ericfranz Updated PR to use git tag to build that version of RPM so that version isn't hardcoded.

**Comment by johrstrom** [comment]
OK so I'm guessing this is finally ready to be pulled in now?

**Comment by treydock** [comment]
I think so.

**Pull request merged**
