### PR TITLE
ood-portal-generator: Serve any /public/maintenance/ file in maint mode

### PR DESCRIPTION
**Pull request by CSC-swesters**
- While in maintenance mode, do not redirect request URIs which start with "/public/maintenance/"

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203563876451004) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by johrstrom** [comment]
Yea I think this is what we'll go for, though I'd like @treydock as a 2nd pair of eyes.

Again - this is not likely to pass tests so if you allow us to edit it (there should be a checkbox somewhere), I can take care and fix the tests if you like.

**Comment by CSC-swesters** [comment]
Hmm, the box is checked (I rechecked it, in case Github is being buggy). Is it an issue that the source for this PR is my personal fork of the ondemand repository? Let me know if there's something I can do.

Thanks for the help with the tests! I personally don't have a Ruby development environment set up, so I appreciate the help :smile:

**Comment by CSC-swesters** [comment]
Also, note that I targeted this PR for the release_2.0 branch, which is what my interest is for the moment. The commit is probably trivial to merge to master as well.

**Comment by johrstrom** [comment]
> Hmm, the box is checked (I rechecked it, in case Github is being buggy). Is it an issue that the source for this PR is my personal fork of the ondemand repository? Let me know if there's something I can do.

OK - I hadn't tried to edit yet (GH isn't showing me that I can or can't), I was just re-confirming that I'd do that work.

> Also, note that I targeted this PR for the release_2.0 branch, which is what my interest is for the moment. The commit is probably trivial to merge to master as well.

Yea, I'll port to 2.1 shortly.

**Comment by johrstrom** [comment]
I didn't forget about this, just now getting time to look into it.  To be clear, this is to add additional assets like images and CSS right?

In any case, I'm testing with CSS file and it's being redirected so looks like the rewrite is rewriting everything all the time such that I cannot request the CSS assets in the same folder.

image

**Comment by CSC-swesters** [comment]
Thanks for returning to this!

It seems like you've misspelled "maintenance" in your path to `bootstrap.min.css`. It's saying "maintanance" at the moment, which doesn't match the regex I proposed.

**Comment by johrstrom** [comment]
🤦‍♂️ you're right. Though when I do it correctly, I still get the html page with a 503 error code.

image

**Comment by johrstrom** [comment]
I think I got it, we need to modify this line too.

https://github.com/OSC/ondemand/blob/4ac701fe852cf46e0fedab52f323481928ad7684/ood-portal-generator/templates/ood-portal.conf.erb#L335

**Comment by johrstrom** [comment]
OK sorry for all the noise, I wasn't even on your branch... It appears to work directly. Sorry again!

**Comment by CSC-swesters** [comment]
Thanks for fixing the tests! No worries about the testing, I'm happy you found the problem :)

As a tip for others wanting to use this feature, once it gets merged, you can use symlinks to your normal assets from the maintenance folder, to avoid duplicating files on the web server. That's how we use it, e.g. symlink: `favicon.ico -> ../favicon.ico` inside the maintenance directory.

It should also be possible to create any subdirectory structures you want inside the maintenance directory, so users can structure their code as they please. I haven't tested that, but I'm fairly certain it works.

I didn't check whether the documentation needs an update, but feel free to point out the correct place, maybe I'll have a stab at that as well!

**Comment by johrstrom** [comment]
docs for this feature are here. If you want to add the symlink helper info, I think that's fine. If not, that's fine too.

https://github.com/OSC/ood-documentation/blob/4e65ead00a024e586ed71378b02f8db1f1bcc9cd/source/customizations.rst?plain=true#L954

I think this change is simple enough to be undocumented. Because it seems to work just the way you'd think it should.

**Review by johrstrom — APPROVED** [review]
Thanks for submitting this!

**Comment by CSC-swesters** [comment]
I submitted a PR with documentation updates to https://github.com/OSC/ood-documentation/pull/755 if you wish to include this in the docs.

**Pull request merged**
