### PR TITLE
Support setting passenger_pool_idle_time

### LINKED ISSUE #1208: make passenger_pool_idle_time configurable
this ticket is to make `passenger_pool_idle_time` configurable for the PUNs as a request from TotalSim who'd like it extended to 10 minutes or so.

### PR DESCRIPTION
**Pull request by treydock**
Fixes #1208

### CODE REVIEW

**Comment by johrstrom** [comment]
Thanks! needs to be added to the example too though.

**Comment by treydock** [comment]
I updated the example config, also made sure to mention that setting `false` can avoid putting this in the NGINX configs.

**Comment by treydock** [comment]
I missed something, which e2e tests picked up.  Running locally I get this when starting PUN:

```
Error -- undefined local variable or method `passenger_pool_idle_time' for #<NginxStage::PunConfigGenerator:0x0000561c34aa7520>
Did you mean?  passenger_root
Run 'nginx_stage --help' to see a full list of available command line options.
```

**Review by johrstrom — APPROVED** [review]
LGTM

**Pull request merged**
