### PR TITLE
fixed bug#1322

### LINKED ISSUE #1322: New file error isn't formatted right
Looks like we need a space here between filename and that. I replicated this by trying to save a filename that's only spaces, so maybe there's some `chomp` funny business here.

image

### PR DESCRIPTION
**Pull request by ayushchatur**
fixed #1322

### CODE REVIEW

**Comment by johrstrom** [comment]
Your commits don't seem to be associated with your GH user. Is it the right `user.email` git config?

**Comment by ayushchatur** [comment]
@johrstrom rebased with correct author

**Review by johrstrom — CHANGES_REQUESTED** [review]
I'm not sure that it is. This still has 3 commits - one of them from the unknown user.

**Comment by ayushchatur** [comment]
raise another #1359

**Pull request closed without merging**
