### PR TITLE
#65 initialize ood-portal if it doesnt exist

### PR DESCRIPTION
**Pull request by johrstrom**
patch for #65.

### CODE REVIEW

**Comment by treydock** [comment]
Patched ood-images vagrant environment and verified this patch does what we need.

**Comment by ericfranz** [comment]
I think it is preferable to add this check to as an option to the checksum check:

```bash
if [[ sha256sum --quiet --status --check $SUM 1>/dev/null 2>&1 ]] || [[ ! -f "$APACHE"  ]]; then
  REPLACE=true
else
  REPLACE=false
end
```

**Comment by ericfranz** [comment]
Then the first time we install what should happen is this block gets executed
https://github.com/OSC/ondemand/pull/66/files#diff-1a1ffb777435f381a87c951c3ba91ce5R79-R84

**Comment by ericfranz** [comment]
I mean https://github.com/OSC/ondemand/blob/1a8be1e22c960ff10ace2e4d30c846d169e06615/ood-portal-generator/sbin/update_ood_portal#L79-L84

**Comment by ericfranz** [comment]
Of course then it will say "Generating Apache config checksum file:" twice.

**Comment by ericfranz** [comment]
Or put above it:

```
echo "Generating new Apache config at: '${APACHE}'"
```

also we should be consistent to use `cat "${NEW_APACHE}" > "${APACHE}" ` or `cp "${NEW_APACHE}" "${APACHE}"` throughout instead of a mix.

**Comment by johrstrom** [comment]
Changed to the one-line check to see if checksum is the same OR file doesn't exist.

**Comment by johrstrom** [comment]
Changed the commit the one liner, @treydock any thoughts on that?

**Comment by treydock** [comment]
I like the one line approach more, reusing existing logic to handle everything.

**Comment by treydock** [comment]
The current changes look good, just get two `Generating Apache config checksum file:` upon first install but that's the only time, not really a big deal.

**Pull request merged**
