### PR TITLE
test ci

### PR DESCRIPTION
**Pull request by johrstrom**
This is just a draft PR to test the CI to see if tests are fialing here too.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201751614874169) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by johrstrom** [comment]
@treydock I'm trying to debug CI failures for 2.0. I'm looking into the unit tests, but can you check out the el8 test failures?

**Comment by treydock** [comment]
Need to update 2.0 package building to use Rocky Linux, the CentOS 8 mirrorlists are gone.

```
Error: Failed to download metadata for repo 'BaseOS': Cannot prepare internal mirrorlist: No URLs in mirrorlist
```

**Comment by treydock** [comment]
@johrstrom I am re-running the jobs. The ondemand-packaging 2.0 branch has Rocky Linux as build environment for EL8.

**Comment by treydock** [comment]
Now tests fail because E2E uses centos8

**Pull request closed without merging**
