### PR TITLE
add a container desktop

### PR DESCRIPTION
**Pull request by johrstrom**
This allows folks to run VDIs or desktops from within a container. It lets users choose what mounts to use and what other arguments to pass to the container runtime. It could support podman or docker as well as singularity.  It's a possible solution for #388. 

I got this to work with a basic centos7 image (base meaning nothing installed, just pulled from dockerhub) with this `submit/container.yml.erb`. 

```ruby
---
script:
  native:
    resources:
      nodes: "<%= bc_num_slots %><%= node_type %>"
  job_environment:
    CONTAINER_IMAGE: "/users/PZS0714/johrstrom/Public/images/sing/centos7_base.sif"
    CONTAINER_CMD: "singularity"
    CONTAINER_ARGS: "-p"
    SEPERATOR: "%"
    CONTAINER_MNTS: "/etc%/usr%/dev:ro%/tmp:/tmp%/home:/home%/fs%/lib:/lib%/lib64:/lib64%/var:/var"
    DESKTOP_CMD: "/usr/bin/bash\ -c\ $PBS_O_WORKDIR/desktops/mate.sh"
```

To test this you use this file for your `submit` along with `attributes.desktop: container`.

### CODE REVIEW

**Comment by xhejtman** [comment]
Do you plan support for port forward and/or websockify stuff? That one is a bit tricky as you need to find free port on host and forward it into container where is sockify running if you want to run interactive desktop in container.

**Comment by ericfranz** [comment]
There is control coupling here - if you imagine `container` script as a function and `CONTAINER_CMD` as the argument that is telling the function how to behave.

It will make the code easier to understand if instead of a single `container` desktop you had `singularity_container` and `podman_container` and `docker_container` desktops.

That would get rid of the `CONTAINER_CMD` and control flow.

**Comment by johrstrom** [comment]
This change only isolates the X11 libraries like MATE or Gnome in the container.  VNC and websockify still boot on the host, which is something I hadn't thought of. That is a much more invasive change to that wrapper, but maybe it's time for a `batch_connect.container` type template?  

In either case, no this doesn't support that because this was an easier change than that and I had just thought all the desktop libraries where the main concern, which this could compensate for.

**Comment by ericfranz** [comment]
>VNC and websockify still boot on the host

Is there anything stopping someone from using an image that has VNC and websockify installed in the image?

**Comment by xhejtman** [comment]
> > VNC and websockify still boot on the host
> 
> Is there anything stopping someone from using an image that has VNC and websockify installed in the image?

Yes. You need to setup portforward from host to container websockify port. And I prefer this as you do not need to mess the host with vnc and/or websockify, you only need to provide image with vnc installed. This is nice and clean path.

However, websockify randomly picks port to listen to from ondemand server connection. Ok, this port can be forced to fixed one using min/max e.g. to 2000. But you need to forward some host port to this 2000 port in container and moreover, overwrite it in connection.yml config. Host port should be preferably random otherwise you cannot run more than one container on a single host. The most safe way imho is to setup the image that internal port 2000 is EXPOSED and use -P paramter to expose it to random port. Tricky part is that you hardly find the random port from inside the container to alter connection.yml from container. And you need to setup connection.yml from the container if you want to setup vnc and websockify in the container.

**Comment by johrstrom** [comment]
> Is there anything stopping someone from using an image that has VNC and websockify installed in the image?

No, but the host ports need to be chosen before the container starts written to the `connection.yml` (which is generally handled by the templates), then passed to the container start command.  

So all this prep work needs to be done up front, which it could in this shell, but it doesn't seem like the appropriate place.

**Comment by xhejtman** [comment]
> > Is there anything stopping someone from using an image that has VNC and websockify installed in the image?
> 
> No, but the host ports need to be chosen before the container starts written to the `connection.yml` (which is generally handled by the templates), then passed to the container start command.
> 
> So all this prep work needs to be done up front, which it could in this shell, but it doesn't seem like the appropriate place.

Well, for podman, we solved this in the following way:
1) we prepared an image with turbovnc+websockify+xfce that has defined EXPOSED port 2000.
2) we set min/man ports for websockify to 2000, so only this port is used in the container.
3) we bind whole host filesystem into container, and using dirty hack, we read podman libpod database in the container to see what is host port number 
4) we overwrite websockify port in connection.yml and things are working

I know this is ugly and better approach is appreciated however, it is not possible without ondemand core support.

**Comment by johrstrom** [comment]
I'll let this sit for another 24 hours, but it looks like I'll probably close it in favor of perhaps making new batch_connect templates or some other solution that can solve port forwarding and environment prep and container startup better.

**Comment by novosirj** [comment]
> Well, for podman, we solved this in the following way:
> 
> 1. we prepared an image with turbovnc+websockify+xfce that has defined EXPOSED port 2000.
> 2. we set min/man ports for websockify to 2000, so only this port is used in the container.

Doesn't this prevent more than one user from running a container on any given compute node?

**Comment by johrstrom** [comment]
> Doesn't this prevent more than one user from running a container on any given compute node?

Docker and podman have network namespaces so things inside the container can start on any port and you just have to forward a port on the host to it. So it looks like you've started on port 2000 to the process but it's actually any port.

In any case, I'm closing this because it doesn't seem to fit everyone's needs.

**Pull request closed without merging**
