### PR TITLE
Update hterm to 1.91 (shells)

### PR DESCRIPTION
**Pull request by Micket**
fixes the problem described in #1369 (however, that issue is not due to the keyboard inputs; just the display output itself. The numerous keycode-issues are still present with no easy fix)

Both old patches re-applied. I can confirm that the fix for https://github.com/OSC/ood-shell/issues/64 is still needed.
I can't verify the necessity of the other keycode fix as I'm unable to reproduce the issue.

Tested on linux with Firefox, Chromium, and Google Chrome.

Taken from https://chromium.googlesource.com/apps/libapps/hterm.org/ (since the sources have been moved around a bit)

### CODE REVIEW

**Comment by johrstrom** [comment]
Thanks for the pull request! I'll take a look at this this week.

**Comment by johrstrom** [comment]
Thanks, I've confirmed that it's the right build. I can't obviously check the 10,000 file - I just rebuilt the same and checked any diff.

I do have one small thing. Can you move this line for #1214 patch down a little bit? They've organized all those `add`s to match the physical keyboard layout. It is a minor thing, but it may make it easier to spot for us in the future.

```javascript
  // Second row.
  // ...
  add(keycapMU, '-_', DEFAULT, c('onZoom_'),  DEFAULT,        c('onZoom_'));
  add(keycapEP, '=+', DEFAULT, c('onZoom_'),  DEFAULT,        c('onZoom_'));

  // Firefox Italian +*.
  add(171, '+*', DEFAULT, c('onZoom_'), DEFAULT, c('onZoom_'));

  add(8,   '[BKSP]', bs('\x7f', '\b'), bs('\b', '\x7f'), DEFAULT,     DEFAULT);
```

**Comment by Micket** [comment]
Done (I made sure to keep the commits separate https://github.com/OSC/ondemand/pull/1426/commits/2c3e5e99aa6a270cb34ea22fa7bbcd4cce5d008b is the 1.91 sources, unmodified since I assume you wanted to verify it).

**Review by johrstrom — APPROVED** [review]
Thanks for this, and the README update too! Which I completely spaced on adding.

**Pull request merged**
