### PR TITLE
Support Ubuntu 20.04 packages with OnDemand 2.0

### PR DESCRIPTION
**Pull request by treydock**

### CODE REVIEW

**Comment by treydock** [comment]
@johrstrom This is now ready for review.  Had to backport quite a bit to support Ubuntu.

**Comment by johrstrom** [comment]
Packages build good in the tests, so that's good, but I need a minute to look stuff over.

**Review by johrstrom — APPROVED** [review]
This looks good. Off the top - I'd like to get an `ood_core` update for that httpd bugfix before an actual release.

**Comment by johrstrom** [comment]
Oh also - those label workflows could be broken so if you merge this those labels may not do anything.

**Comment by treydock** [comment]
Looks like the issues from labels worked.

**Pull request merged**
