### PR TITLE
3.1.8

### PR DESCRIPTION
**Pull request by johrstrom**
Here are a bunch of things we need to backport to 3.1. They're all bug fixes or optimizations.

### CODE REVIEW

**Review by ashton22305 — APPROVED** [review]
Looks good!

**Comment by CSC-swesters** [comment]
Thanks for backporting these! Do you plan to tag a release 3.1.8 and package it soon? We're interested in deploying it as soon as it's ready. Or is there something which is still pending that I've missed?

**Comment by johrstrom** [comment]
There is something pending that I'm working on this week.

**Comment by CSC-swesters** [comment]
Got it, thanks. If the timelines align, Robin's optimization in #3804 would be a nice backport candidate too, once it's reviewed and accepted.

**Pull request merged**
