### PR TITLE
Bc templates

### LINKED ISSUE #2973: save templates into the users' profile
Once #2958 is merged let's refactor where these templates are being stored.

Let's start using the users' profile file for storing this information in it. Currently (at the time of writing) we're only using this file to store which profile the user has selected. Let's expand this so that it also stores prefill templates for batch connect apps.

This may require some thought as CurrentUser holds all this logic currently when it probably shouldn't. IDK where this should go off hand, but I don't think CurrentUser should have it as we want to be able to use CurrentUser in the boot stack (i.e., it shouldn't rely on any external library).

### PR DESCRIPTION
**Pull request by johrstrom**
Fixes #2973 - though I want to add some more tests.

### CODE REVIEW

**Comment by Oglopf** [comment]
I'm having some `sbatch` errors around some missing fields when I go to launch.

Steps to reproduce:
1. save a template and launch the app
2. come back into the app form again
3. select the prefill template you just saved
4. but now, change the cluster or time field
5. try to launch

This looks to throw errors each time i've done this. Something to do with selecting the template, but then "changing your mind" and tweaking some fields seems to break the submissions.

**Comment by johrstrom** [comment]
> I'm having some sbatch errors around some missing fields when I go to launch under some specific but likely conditions.

Thanks, I couldn't replicate so I took a look at your logs. I don't think it's an issue with this feature - I think you just can't submit to the `debug` queue for longer than 1 hour. 

I had to look this up - but you can see in these docs that the `debug` queue has a 1 hour time limit.

https://www.osc.edu/resources/technical_support/supercomputers/pitzer/batch_limit_rules

**Comment by Oglopf** [comment]
Ha! Thanks! I didn't know that and the error didn't indicate anything about that. 

That was the only weird thing I noticed, everything else looked good!

**Review by Oglopf — APPROVED** [review]
LGTM.

**Pull request merged**
