### PR TITLE
Issue#1902 added alt text to the navbar img tag

### PR DESCRIPTION
**Pull request by SaumyaBhushan**
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202239213072566) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by SaumyaBhushan** [comment]
Please Review.

**Comment by johrstrom** [comment]
We'd like to have something translatable for folks. I.e., they could configure `Ohio SuperComputer Center OnDemand`.  You may see this sprinkled through the codebase by calling the function `t` or `I18n.t`.

Here's an example you can follow that took static text and made it translatable.
https://github.com/OSC/ondemand/pull/1984

Secondly - the default text is a replacement for the logo, not a reference to the logo itself, so it should probably be something more like `this open ondemand instance` so folks using screen-readers will recognize that (a) it's a link somewhere and (b) the alt text is telling them _where it's a link to_.

**Comment by johrstrom** [comment]
We're also always looking for new translations if you're multi-lingual. I sadly am not, but I don't know how many good first issues we'll have at this rate!

**Comment by SaumyaBhushan** [comment]
I have made suggested changes. Does it looks good now?

**Review by johrstrom — APPROVED** [review]
works for me!

**Pull request merged**
