### PR TITLE
Prefill templates

### LINKED ISSUE #2973: save templates into the users' profile
Once #2958 is merged let's refactor where these templates are being stored.

Let's start using the users' profile file for storing this information in it. Currently (at the time of writing) we're only using this file to store which profile the user has selected. Let's expand this so that it also stores prefill templates for batch connect apps.

This may require some thought as CurrentUser holds all this logic currently when it probably shouldn't. IDK where this should go off hand, but I don't think CurrentUser should have it as we want to be able to use CurrentUser in the boot stack (i.e., it shouldn't rely on any external library).

### PR DESCRIPTION
**Pull request by Oglopf**
Fixes #2973

### CODE REVIEW

**Comment by Oglopf** [comment]
Weird. These are saving as JSON in data/batch_connect/sys/bc_osc_paraview/prefill_templates/.

session_contexts_controller.rb#save_template is currently being used, yank that out since we don't want the json and replace with module behavior as well.

**Comment by Oglopf** [comment]
Ran into another issue. These templates will just populate without regard for what app they are in currently. So, prefill settings for paraview will show up for jupyter, etc.

I need to check if this was true before and see how they handled it or make a filter for that.

**Comment by Oglopf** [comment]
Plan is to just add another layer for the app names to hold the respective data in the prefill_template section.

**Comment by Oglopf** [comment]
was really confused with an issue until i realized this is currently setup to do some amount of saving in the controller, ,then more in the model. 

yank the saving logic from the controller for the templates as a controller shouldn't be managing this logic.

Let the usersettingstore handle the sanitization of the `safe_name` and the `updated_settings`.

**Comment by Oglopf** [comment]
I've got myself a bit turned around. Is the `save_templates` supposed to be for other templates in the future or for the prefills? 

I'm also a bit confused if the json is supposed to be totally converted to some type of yaml, or is the idea yaml with keys that have json objects?

**Comment by Oglopf** [comment]
The data structure as I understood what was asked:
```yaml
---
prefill_templates:
  apps:
    - juypter:
        - test3: '{"cluster":"pitzer","account":"PZS0714","mode":"1","bc_num_hours":"1","node_type":"any","cuda_version":"cuda/8.0.44","num_cores":"1","version":"app_jupyter/3.1.18","bc_email_on_started":"0"}'
        - test4: '{"cluster":"pitzer","account":"PZS0714","mode":"1","bc_num_hours":"1","node_type":"any","cuda_version":"cuda/8.0.44","num_cores":"2","version":"app_jupyter/3.1.18","bc_email_on_started":"0"}'
    - paraview:
        - test2: '{"version":"paraview/5.8.0","account":"PZS0714","bc_num_hours":"1"}'
```

**Comment by johrstrom** [comment]
While I was hacking on this, this is what I came up with. I know for sure we'd want to cast it all to YAML instead of stringifying that json and using that as the value.

```yaml
---
batch_connect_templates:
  sys/bc_osc_iqmol:
  - cluster: owens
    account: PZS0714
    bc_num_hours: '1'
    num_cores: '1'
    node_type: any
    ood_bc_template_name: new one
  - cluster: owens
    account: PZS0714
    bc_num_hours: '5'
    num_cores: '5'
    node_type: any
    ood_bc_template_name: 5s all day
```

**Comment by Oglopf** [comment]
I guess looking at the structure there I'm a bit confused. I thought this was going to hold more than just these batch connect prefill templates, which is why it wasn't a full fledged model and a concern instead? That was the only reason i had an `apps` category.  I just want to check is all, what you have is much easier to accomplish if that's the structure we want.

**Comment by johrstrom** [comment]
> I thought this was going to hold more than just these batch connect prefill templates

Sure there are & will be more siblings to what you call `prefill_templates`, but no children other than this feature.

**Pull request closed without merging**
