### PR TITLE
Sets up MotdConcern for shared use

### PR DESCRIPTION
**Pull request by HazelGrant**
Fixes https://github.com/OSC/ondemand/issues/2732

### CODE REVIEW

**Comment by johrstrom** [comment]
One clue in that comment above is that `_motd` is being rendered but not `_motd_markdown`.

**Comment by HazelGrant** [comment]
Apologies for this taking so long, especially considering what I found. I was finally able to figure out why I couldn't get MOTD to render anywhere - it's simply because I didn't have MOTD_PATH set. However, once I set that, I was able to confirm that the MOTD widget works for custom pages with the changes from this PR (but not without) on my end. So I'm uncertain why this PR would be working for me and not you.

**Comment by johrstrom** [comment]
> Apologies for this taking so long, especially considering what I found. I was finally able to figure out why I couldn't get MOTD to render anywhere - it's simply because I didn't have MOTD_PATH set. However, once I set that, I was able to confirm that the MOTD widget works for custom pages with the changes from this PR (but not without) on my end. So I'm uncertain why this PR would be working for me and not you.

No issues. Can you let me know the format (`MOTD_FORMAT`) that you use? Could it be it's working for some formats and not others? (I'm using `MOTD_FORMAT="markdown"` in my example.)

Also - I'll take another look and see if there's something off on my side.

**Comment by HazelGrant** [comment]
I was using .txt, but I just tested and markdown also works for me.

**Review by johrstrom — APPROVED** [review]
1,000 apologies - I must have tested this on the current master branch 🤦‍♂️.

You are right, this does work as expected. However, I'm looking into why the expression `@motd = MotdFile.new.formatter` can raise an error and if we need to refactor that.

A quick glance indicates it doesn't raise an error (it seems to rescue itself), so there could be additional cleanup tasks here.

**Pull request merged**
