### PR TITLE
Use latest ood_packaging gem and cleanup some EL7 things

### PR DESCRIPTION
**Pull request by treydock**

### CODE REVIEW

**Comment by johrstrom** [comment]
Do we have any distributions that use Ruby 2.7?  We've got a flaky test there where globs work differently in Ruby 2.7. So I'm thinking if we don't actually have ruby 2.7 as a deploy target - now's likely a good time to remove that entirely.

**Comment by treydock** [comment]
Marked draft while I address some missing package issues from dropping EL7.  Have to rebuild passenger/nginx with correct runtime version.

**Comment by johrstrom** [comment]
> Ubuntu 20.04 is still using Ruby 2.7.

OK - well that unit test that's failing now I'll try to sort out.

**Comment by treydock** [comment]
Fixed the e2e tests that were failing.

**Comment by johrstrom** [comment]
> Fixed the e2e tests that were failing.

Cool - I'll fix that unit test that's failing today.

**Review by johrstrom — APPROVED** [review]
LGTM

**Pull request merged**
