### PR TITLE
Added saved settings widget

### PR DESCRIPTION
**Pull request by abujeda**
Created a saved settings widget to display the saved settings in the homepage.

Sample configuration:
```yaml
    dashboard_layout:
      rows:
        - columns:
            - width: 12
              widgets:
                - "saved_settings"
                - "pinned_apps"
```

### CODE REVIEW

**Comment by abujeda** [comment]
Some screenshots of the widget:
Screenshot 2024-05-08 at 13 20 01

Screenshot 2024-05-08 at 13 20 10

**Comment by johrstrom** [comment]
Hey, sorry for the delay -  I'm preparing for [Summer Institute](https://www.osc.edu/education/si) which is eating a lot of my time/focus. Which is to say - I may not get to this quickly.

**Comment by johrstrom** [comment]
I think this conflicts with the bootstrap 5 upgrade we just did.

**Review by johrstrom — APPROVED** [review]
LGTM

**Pull request merged**
