### PR TITLE
Allow oidc_crypto_passphrase to be set for ood-portal-generator

### PR DESCRIPTION
**Pull request by treydock**
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204589926966692) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by treydock** [comment]
@johrstrom This is a result of a request on Discourse.  Should I back port this relatively simple fix to 2.0 ?

**Review by johrstrom — APPROVED** [review]
I assume you mean 3.0? Sure.

**Comment by treydock** [comment]
Oh I meant 2.0, are we still supporting 2.0 or only back porting into 3.0?

**Comment by johrstrom** [comment]
> Oh I meant 2.0, are we still supporting 2.0 or only back porting into 3.0?

Yea I feel like we should only support one version at a time. Just because we have so many other things going on.

**Comment by treydock** [comment]
Sounds good.

**Pull request merged**
