### PR TITLE
update uppy for dependabot

### PR DESCRIPTION
**Pull request by matt257**
update uppy for dependabot to update ws 

update uppy and dependencies,
don't add new dependencies this time

### CODE REVIEW

**Comment by matt257** [comment]
uppy is working and tests are passing. there is no ability to upload empty directories (in production a js error happens). 
these changes get rid of the error but leave the functionality of uppy_ops.js the same

**Comment by johrstrom** [comment]
I'll take a look into how production currently works. It seems to me that yes uploading an empty directory won't do anything, but what about a directory that has a file and another empty directory?

**Comment by johrstrom** [comment]
OK - uploading something like this, even to production, doesn't create the empty directory. 

```
test/
    some_file.txt
    empty_dir/
```

I guess it's time to inspect this code block to figure out what it's actually doing.

**Comment by johrstrom** [comment]
Also - it looks like the commit history is off. merges usually work for me, not quite sure how you got into that state - but you may have to cherry-pick and create a new pull request.

**Comment by matt257** [comment]
Thanks! I'll close this and try to open a new pull request with fixed commit history. Should we open an issue about the empty directory issue?

**Pull request closed without merging**
