### PR TITLE
Initial script model

### PR DESCRIPTION
**Pull request by Oglopf**
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203969024301736) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by Oglopf** [comment]
Second attempt at #1861

**Comment by Oglopf** [comment]
Sorry, should be in draft, not done yet.

**Comment by Oglopf** [comment]
I've always been curious how we do `initialize` here and this is a perfect place to discuss this.

I've put keyword values in for the initializer, but in other areas of the code i've seen this patter:
```
def initialize(opts = {})
  thing1 = opts.fetch(:thing1, nil)
  thing2 = opts.fetch(:thing2, nil)
  ...
end
```

Which looks to expect a hash then extract but set `nil` values if nothing is there. Should I be using this pattern or are keyword arguments ok?

**Comment by johrstrom** [comment]
This is going to be very hard to get right without the views & controllers. Like `id` for example is going to be generated by the controller for sure, and passed to the script. 

Or at least the script has something like this that the controller uses to generate the next `id`.
```
  self.def highest_id
    # ...
  end
```

I mean, without controllers and views, we really don't know what works and what's _required_.  So my take is, if you're only going to do the model, make it as simple and small as you can because the actual consumers of it (controllers & views) are going to dictate what it needs to do.

**Comment by Oglopf** [comment]
Ok, I can close this or we can merge this and I can move onto whichever you prefer, views or controllers.

**Comment by johrstrom** [comment]
> Which looks to expect a hash then extract but set nil values if nothing is there. Should I be using this pattern or are keyword arguments ok?

I would say 1 hash/`*args` (IDK if that's right, I meant the thing so folks don't have to splat) we extract things from is better.

Honestly I think it's just a matter of taste, but it seems nicer to accept anything than to add arguments in the interface.

**Comment by Oglopf** [comment]
We decided to have the `controller` and `view` scaffolding in place first before doing work on the `model`.

**Pull request closed without merging**
