### PR TITLE
Fixed session test after updates to the bc_jupyter app fixture

### PR DESCRIPTION
**Pull request by adaybujeda**
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203458445351431) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by adaybujeda** [comment]
This is to fix the session test after changes introduced to the bc_jupyter fixture in the `Clamp bugfix` commit
https://github.com/OSC/ondemand/commit/9e524011db2ce45ac3b280a07bfe067e13dc645f

**Review by johrstrom — APPROVED** [review]
Kind of curious as to why this doesn't have a merge conflict as I made the same update in #2389. Here goes nothing...

**Comment by adaybujeda** [comment]
Fixed by commit: https://github.com/OSC/ondemand/commit/b022836525306a4fde67619e8f8806bd0edef568
Closing

**Comment by johrstrom** [comment]
Both of us clicking here, I was about to merge and pray it didn't conflict.

**Pull request closed without merging**
