### PR TITLE
convert data to human sizes on the client

### PR DESCRIPTION
**Pull request by johrstrom**
Convert data to human sizes on the client.

This is an optimiztation found in #3026. I found that rails takes some time to do this calculation, so we can push it to the client instead in an attempt to speed up the responses.

### CODE REVIEW

**Review by Oglopf — APPROVED** [review]
This works and looks good.

**Review by Oglopf — APPROVED** [review]

**Comment by stdweird** [comment]
@johrstrom out of curiosity, why doesn't this require a modification to the jbuilder as well? does it now generate an empty "human_size" key?

**Comment by johrstrom** [comment]
🤦‍♂️ I missed that. It's still in the json, only evaluated as nil. The calculation to generate it was what was so expensive. Having `nil` there isn't great, but shouldn't really impact the response. I'll fix in the next release, but don't think I can back port it until there's something more.

https://github.com/OSC/ondemand/blob/740a484b25f39ec21692111fdb27854bf060b69d/apps/dashboard/app/views/files/index.json.jbuilder#L19

**Comment by stdweird** [comment]
no worries wrt backporting/fixing, i was just wondering why that wouldn't be needed.

**Pull request merged**
