### PR TITLE
Increase timeout as Ubuntu 24.04 arm64 builds are slow

### PR DESCRIPTION
**Pull request by treydock**

### CODE REVIEW

**Comment by treydock** [comment]
For now I'll have to build both amazon and ubuntu 24.04 aarch64 locally as my laptop is arm64 so those builds are fast.

**Comment by treydock** [comment]
At some point we need to possibly leverage arm64 Github Actions which I saw a blog post is now a thing.

**Comment by johrstrom** [comment]
> At some point we need to possibly leverage arm64 Github Actions which I saw a blog post is now a thing.

Alan's often talked about paying for github support. The only issue I see here is some sort of sync between github and yum.osc.edu that we'd have to work out (and probably signing RPMs?).

**Review by johrstrom — APPROVED** [review]

**Comment by treydock** [comment]
> The only issue I see here is some sort of sync between github and yum.osc.edu that we'd have to work out (and probably signing RPMs?).

I think this would be possible.  We'd have to add the GPG private key and SSH key to Github org as secrets that can be bootstrapped into Actions.  I'd likely have to open up port 22 on the repo server which I'm not thrilled about but might be able to limit the firewall rule to subnet(s) used by Github Action hosts if those are documented and accurate.  One option is using OSC hardware to run the Github Actions, but there are security issues as you can open up your internal infrastructure to malicious code being run from PRs.  There may be ways to mitigate this but there are big warnings on Github's docs about this feature.

**Pull request merged**
