### PR TITLE
use local storage for db files

### PR DESCRIPTION
**Pull request by johrstrom**
This moves db files to local storage instead of NFS storage. I'm not entirely sure it's bug free as it deals with creating directories through packaging. So we'll likely have to see in a nightly if this works.

In draft for a moment while I write some e2e tests.

### CODE REVIEW

**Comment by johrstrom** [comment]
@treydock PTAL - the unit tests are flaky for another reason.

**Comment by treydock** [comment]
Would it be possible to setup the `/var/lib/ondemand/<user>` directory as root via nginx-stage so that `/var/lib/ondemand` doesn't need to be world writable?  Having a world writable location like that will almost certainly upset numerous automated security checks like CIS benchmarks that disallow world writable other than `/tmp`.  Also having a world writable location on `/var` is a stability risk as malicious user at OSC via OnDemand could fill up `/var` and then crash the VM since numerous critical services need to write to that partition including things like log files.

**Comment by johrstrom** [comment]
> Would it be possible to setup the /var/lib/ondemand/<user> directory as root via nginx-stage so that /var/lib/ondemand doesn't need to be world writable? 

Yea that sounds fine.

> as malicious user at OSC via OnDemand could fill up /var and then crash the VM since numerous critical services need to write to that partition including things like log files.

Not quire sure how to solve for this, they could still blow up `/var/lib/ondemand/$USER`.

**Comment by treydock** [comment]
> Not quire sure how to solve for this, they could still blow up `/var/lib/ondemand/$USER`.

This would be something that would have to be solved outside OnDemand by making `/var/lib/ondemand` a dedicated partition, maybe mounting with `noexec` unless things will have to be executed out of that location.

**Comment by johrstrom** [comment]
I'm going to close this as I don't believe it's viable.

**Pull request closed without merging**
