### PR TITLE
Add basic logrotation of PUN logs

### PR DESCRIPTION
**Pull request by treydock**

### CODE REVIEW

**Comment by johrstrom** [comment]
Why not add our `weekly` and `rotate 52` directives? I get that this is a basic config, but I feel like those are super liberal but still put _some_ limits in place.

**Comment by treydock** [comment]
It's not really appropriate to assume how often people want logs rotated and how many to keep. That is typically defined globally in `/etc/logrotate.conf`.  The stock logrotate configs for `/etc/logrotate.d` that come from other software stacks do not assume a rotation period or retention so I opted to follow that pattern.

**Comment by MorganRodgers** [comment]
If there are other knobs for log rotation such that users do not have to mess with RPM installed files, then I think that this is good to go as is. @johrstrom thoughts? Or shall we merge?

**Comment by johrstrom** [comment]
I'm fine with this.

**Pull request merged**
