### PR TITLE
restructure a little to get a better layout

### PR DESCRIPTION
**Pull request by johrstrom**
This restructures the projects#show page a little to get a better/columnar layout.

### CODE REVIEW

**Review by ashton22305 — COMMENTED** [review]
When the screen is a certain width, the tables will start to escape the cards that contain them.
image

**Comment by johrstrom** [comment]
Thanks! I can take a look.

**Comment by johrstrom** [comment]
> When the screen is a certain width, the tables will start to escape the cards that contain them.

My feeling is to kind of defer it. If I look at what a tablet/phone does its OK. There's no actual device of this size/width. I feel like it's only us/developers who will encounter this when they open their dev tools to be that wide.

**Review by ashton22305 — APPROVED** [review]
In that case, this looks good to me!

**Pull request merged**
