### PR TITLE
Update default issue milestone to Needs Triaged

### PR DESCRIPTION
**Pull request by msquee**
This PR updates the default milestone assigned to an issue to Needs Triaged.

### CODE REVIEW

**Comment by msquee** [comment]
@ericfranz We could improve this further, what if we had a cronjob [1] that ran every two weeks so that if an issue still has a _Needs Triaged_ tag, we move it to the _Backlog_.

[1] https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule

**Comment by johrstrom** [comment]
Yea there's a whole [actions](https://github.com/actions) repo and the schema you can do `on.schedule` like a cron-tab (I was thinking about adding a stale tag after so many days of non-activity). 

But I'm wondering if this isn't better suited for labels instead of milestones?  I know for sure what the 'version N' milestone gives us, but I'm not sure what a 'needs triaged' milestone does?  When it does get triaged, does it go to a different milestone?

**Comment by ericfranz** [comment]
>issue still has a Needs Triaged tag, we move it to the Backlog

Talked offline with @johrstrom. We want to keep issues in Needs Triaged till they are reviewed by us. Any automation that would be interesting would be emails about stale issues i.e. if an issue has been in the Needs Triaged for more than a week and not addressed or something like that.

But we can merge this in.

**Comment by ericfranz** [comment]
>When it does get triaged, does it go to a different milestone?

To clarify this, if we visualized the milestones on a kanban board it would look like this:

screen 2020-03-11 at 4 13 47 PM

The needs triaged is like the "new" column - where all cards/issues start. For any in here, it is our goal to make a decision about these as soon as possible to move them into one of the others, or close it as not doing. We want to keep the number of issues in Needs Triaged to zero.

Of course this could also be achieved by a label in backlog, but I like to think of an issue being in Backlog (as opposed to On Deck or a release milestone) because we made that decision.

**Pull request merged**
