### PR TITLE
batch connect auto add change handlers

### PR DESCRIPTION
**Pull request by johrstrom**
First attempt at #851. Currently in draft because it's not very solid (some hard coded stuff), but I wanted to give folks a heads up.

Right now this only responds to options for cluster (that's the hard coded bit), but the idea is it could respond to anything.

This needs:
- [x] tests
- [x] feature flag

### CODE REVIEW

**Comment by johrstrom** [comment]
This works at this point. 

I know these work automatically. Note that we're only responding to `false` settings. Everything is shown by default and these rules _hide_ any given option.
```yaml
data-option-for-cluster-oakley: false
data-option-for-node-type-any: false
```

**Comment by johrstrom** [comment]
With tests and a feature flag this is ready for review. I don't think the javascript is optimial - but with test cases that test the feature, not the code directly, we can refactor and build on it.

**Comment by Oglopf** [comment]
When running on test in my dev dashboard I noticed that for the Jupyter app, when selecting the Pitzer Cluster, I don't see a change in the CUDA Version data-options reflecting what's in the `form.yml.erb` file.

To make sure I'm understanding right, I'd expect the `data-option-for-<cluster>` for `cuda_version` in the `form.yml.erb` in the block below to hide versions in the form that have a `false` value associated with them:
<pre>
    options:
      - [ 
          "cuda/8.0.44",    "cuda/8.0.44",
          data-option-for-owens: true,
          data-option-for-pitzer: false,
          data-option-for-kubernetes: false,
          data-option-for-kubernetes-test: false,
          data-option-for-kubernetes-dev: false  
        ]
</pre>

But when I select `pitzer` as a cluster, I still see `cuda/8.0.44` which doesn't seem right from what I'd expect. 

Maybe I am missing something though.

**Comment by johrstrom** [comment]
Yea the way we setup the old apps the cluster is assumed. You see you have `data-option-for-pitzer` when it should be `data-option-for-cluster-pitzer`.

This allows us to attach to any form element, not just clusters.  You see the tests attach changes in `node_type` to change the `python_version`.

**Comment by Oglopf** [comment]
Ok, I was just worried when it pulls into master that it may start rendering form options in unexpected ways since it seems to do that with the jupyter app on test. I get that's because of how the `form.yml.erb` is setting up those data-options, but it sounds like some apps will just have to have some changes made in how the options are named ultimately? Or I'm still totally missing the point..

**Comment by johrstrom** [comment]
Yes they'll have to change if they use the same naming conventions. It will break some apps I'm sure, but that's why there's a feature flag to enable it. It's disabled by default - so folks will be able to enable it in their dev environment and work through updates, then enable it in prod when they're ready.

**Review by Oglopf — APPROVED** [review]
LGTM.

**Pull request merged**
