### PR TITLE
ood-portal-generator: Use proxy_server in http rewrites

### PR DESCRIPTION
**Pull request by CSC-swesters**
- Avoid double rewrites for http (non-https) rewrites, by setting the correct proxy_server value the first time.

### CODE REVIEW

**Comment by CSC-swesters** [comment]
This should fix #2869.

**Comment by johrstrom** [comment]
Thanks for the updates! Do you want me to update tests? I'm happy to take care of that.

**Comment by CSC-swesters** [comment]
If you could do that, I would certainly appreciate it! Thanks!

**Comment by CSC-swesters** [comment]
@johrstrom I think I managed to fix the tests myself. It would seem that the current test failures are unrelated to my changes. Do you agree? Perhaps a rebase against the master branch would help?

I'll try force pushing the same commits on top of a rebased master branch, as a test.

**Comment by johrstrom** [comment]
Yea a thousand apologies for the delay. I had a program teaching high school kids for 2 weeks then I was on vacation last week.

> @johrstrom I think I managed to fix the tests myself. It would seem that the current test failures are unrelated to my changes. Do you agree? Perhaps a rebase against the master branch would help?

Yes the tests are failing from our side. It should only require me closing this PR and re-openeing it to reset what the tests will merge against. You shouldn't have to do anything more, I'd like to sort through fixing the tests today.

**Comment by CSC-swesters** [comment]
No worries, I hope you had a good vacation! :slightly_smiling_face: It's good that this change gets in before the next release, at least! Thanks again!

**Review by johrstrom — APPROVED** [review]
Thanks for the bugfix!

**Pull request merged**
