### PR TITLE
Adding custom completed.{md, html}.erb

### PR DESCRIPTION
**Pull request by canoalberto**
Adding the option to have a custom completed.{md, html}.erb to show up only when the job is completed (e.g. to show a download link with an output file from the job)

### CODE REVIEW

**Comment by johrstrom** [comment]
Hi! thanks for the feature. It appears you need this diff to fix the test cases.

[diff.txt](https://github.com/OSC/ondemand/files/13779391/diff.txt)

**Review by johrstrom — APPROVED** [review]
Thanks for the contribution!

**Comment by simonLeary42** [comment]
so if my job creates `completed.md.erb` in its current working directory (where I go when I click on "session ID"), I should see a message after completion? It's not working for me.

**Comment by johrstrom** [comment]
I don't think this feature has been released yet. It'll be in 4.0.

**Pull request merged**
